# Generated by Django 5.2.6 on 2025-09-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('victim', 'Victim'), ('volunteer', 'Volunteer'), ('donor', 'Donor'), ('admin', 'Admin')], max_length=20)),
                ('language_preference', models.CharField(default='English', max_length=20)),
                ('verification_status', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('urgency_level', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('voice_message_path', models.FileField(blank=True, null=True, upload_to='voice/')),
                ('priority_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
