# Generated by Django 5.2.6 on 2025-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_donation_donation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Relief', 'Relief'), ('Medical', 'Medical'), ('Shelter', 'Shelter'), ('Other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('volunteer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='aidrequest',
            old_name='request_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='aidrequest',
            name='priority_score',
        ),
        migrations.RemoveField(
            model_name='aidrequest',
            name='urgency_level',
        ),
        migrations.RemoveField(
            model_name='aidrequest',
            name='voice_message_path',
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='aid/photos/'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='aid/voice/'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('shelter', 'Shelter'), ('medical', 'Medical'), ('clothes', 'Clothes'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
